language: php

dist: xenial
addons:
  apt:
    packages:
    - build-essential
    - cmake
    - libpcre3-dev
    - libgmp-dev
    - libssl-dev

php:
  - 7.1.19

before_install:
  # Cassandra Dependencies
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.24.0/libuv1_1.24.0-1_amd64.deb && sudo dpkg -i libuv1_1.24.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/dependencies/libuv/v1.24.0/libuv1-dev_1.24.0-1_amd64.deb && sudo dpkg -i libuv1-dev_1.24.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.11.0/cassandra-cpp-driver_2.11.0-1_amd64.deb && sudo dpkg -i cassandra-cpp-driver_2.11.0-1_amd64.deb
  - wget http://downloads.datastax.com/cpp-driver/ubuntu/16.04/cassandra/v2.11.0/cassandra-cpp-driver-dev_2.11.0-1_amd64.deb && sudo dpkg -i cassandra-cpp-driver-dev_2.11.0-1_amd64.deb
  - pecl channel-update pecl.php.net && pecl install cassandra
  # PHP-cs-fixer
  - composer global require --dev 'friendsofphp/php-cs-fixer'
  - export PATH="$PATH:$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin"

install:
  - composer install --prefer-dist -n -o

script:
  - php-cs-fixer fix --dry-run --diff --no-ansi
  - vendor/bin/atoum

